author: kamadorueda
enableGitInfo: true
enableEmoji: true
enableRobotsTXT: true
baseURL: https://kamadorueda.github.io/
defaultContentLanguage: en
languageCode: en
menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
params:
  author: kamadorueda
  authorimage: avatar.png
  copyright: "Kevin Amado"
  dateformat: Jan 2, 2006
  # description: Technology, thoughts, opinions
  highlightjs: true
  highlightjsstyle: github
  license: CC BY-NC-SA 4.0
  licenseURL: https://creativecommons.org/licenses/by-nc-sa/4.0/
  mainSections:
    - about
    - posts
  postNavigation: true
  relatedPosts: true
  include_toc: true
  showBuiltWith: true
  social:
    email: kamadorueda@gmail.com
    github: kamadorueda
    linkedin: kamadorueda
permalinks:
  posts: /:year/:month/:slug/
  vn: /:year/:month/:slug/
publishDir: docs
theme: hyde-hyde
title: Kevin Amado
