baseURL: https://kamadorueda.com/
defaultContentLanguage: en
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
languageCode: en
menu:
  main:
    - identifier: contact
      name: Contact
      url: /contact/
    - identifier: posts
      name: Posts
      url: /posts/
module:
  imports:
    - path: github.com/adityatelange/hugo-PaperMod
outputs:
  home:
    - HTML
    - RSS
    - JSON
params:
  # ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  ShowReadingTime: true
  # ShowShareButtons: true
  ShowToc: true
  ShowWordCount: true
  TocOpen: true
  editPost:
    Text: Suggest Changes
    URL: https://github.com/kamadorueda/kamadorueda.github.io/edit/main/content
    appendFilePath: true
  profileMode:
    buttons:
      - name: Contact
        url: /contact/
      - name: Posts
        url: /posts/
    enabled: true
    imageHeight: 120
    imageTitle: <title of image as alt>
    imageWidth: 120
    subtitle: This place is about technology, opinion, and thoughts
    title: "Welcome to my website \U0001F44B"
  socialIcons:
    - name: LinkedIn
      url: https://linkedin.com/in/kamadorueda
    - name: GitHub
      url: https://github.com/kamadorueda
    - name: Email
      url: mailto:kamadorueda@gmail.com
permalinks:
  posts: /:year/:month/:slug/
  vn: /:year/:month/:slug/
publishDir: docs
title: Kevin Amado's Website
